In [88]:
import numpy as np
import itertools
import pandas as pd
import json
import sys

In [89]:
# 1 -- loading the data
with np.load('../find_the_most_common_ingredients/simplified-recipes-1M.npz', allow_pickle=True) as data:
    recipes = data['recipes']
    ingredients = data['ingredients']

print("data is read")
# an example

data is read


In [90]:
print(recipes[0:5])

[array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21])
 array([ 198,  249,    2,  194, 1884,  791,  965,  423,   53,   48,  798,
         31,  362, 1031,   94,   26,    8])
 array([ 328,  263,   62,   46,  445,   55, 1196,   82,  664,    3,  602,
         10,    7,    6,    1,  128,   61,  141,    0,  262,  140,  655,
         21,    8,   23,   84])
 array([ 988, 1307])
 array([  14, 1117,  998, 1010,    9,   30,   18,   29,  214, 1752, 1477,
          1,  132,  196,  658, 1301,   26,  113])]


In [91]:
print(ingredients[42])

leaves


In [92]:
print(ingredients[recipes[0]])

['basil leaves' 'focaccia' 'leaves' 'mozzarella' 'pesto' 'plum tomatoes'
 'rosemary' 'sandwiches' 'sliced' 'tomatoes']


In [93]:
# 2 -- flatten the whole recipes

merged = np.array(list(itertools.chain(*recipes)))
merged

array([ 233, 2754,   42, ...,   23,   84,  102])

In [107]:
# 3 -- histogram
histo = np.histogram(merged, bins=np.max(merged))
histo[0]

array([451350, 412860, 309790, ...,    112,    210,    242])

In [108]:
# 4 -- converting the frequencies to a data frame

df = pd.DataFrame({'ingredient': ingredients[histo[1][:-1].astype(int)], 'freq': histo[0]})
df.head(20)

ingredient    freq
0           salt  451350
1         pepper  412860
2         butter  309790
3         garlic  311255
4          sugar  349623
5          flour  243109
6          onion  223779
7      olive oil  216157
8          water  211913
9         ground  221839
10         olive  217445
11        powder  152317
12        sliced  173659
13          eggs  167961
14  black pepper  164505
15          milk  157669
16        cheese  158280
17         cream  145604
18         lemon  138790
19       chicken  142299

In [114]:
# 5 -- sorting to find the most common ones
#df.sort_values('freq', ascending=False, inplace=True, ignore_index=False)
#df_sorted = df
df_sorted.head(20)

ingredient    freq
0           salt  451350
1         pepper  412860
2          sugar  349623
3         garlic  311255
4         butter  309790
5          flour  243109
6          onion  223779
7         ground  221839
8          olive  217445
9      olive oil  216157
10         water  211913
11        sliced  173659
12          eggs  167961
13  black pepper  164505
14        cheese  158280
15          milk  157669
16        powder  152317
17         sauce  146428
18         cream  145604
19       chicken  142299

In [110]:
#df_sorted_index = df
#df_sorted_index.sort_values('freq', ascending=False, inplace=True, ignore_index=True)

In [106]:
df_sorted_index.head(20)

ingredient    freq
0           salt  451350
1         pepper  412860
2          sugar  349623
3         garlic  311255
4         butter  309790
5          flour  243109
6          onion  223779
7         ground  221839
8          olive  217445
9      olive oil  216157
10         water  211913
11        sliced  173659
12          eggs  167961
13  black pepper  164505
14        cheese  158280
15          milk  157669
16        powder  152317
17         sauce  146428
18         cream  145604
19       chicken  142299

In [102]:
df_sorted.index.difference(df_sorted_index.index)

Int64Index([], dtype='int64')

In [46]:
# 6 -- extract the common 100
#nr_comm = int(sys.argv[1])

#tmp = list(df['ingredient'].iloc[0:nr_comm])
#print("the ", nr_comm, " most common ingredients are: \n")
#print(tmp)

ValueError: invalid literal for int() with base 10: '-f'

In [ ]:
# 7 -- saving to a file

filename = 'common_ingredients_' + str(nr_comm) + '.dat'
with open(filename, 'w') as f:
    f.write(json.dumps(tmp))
print('\nthe info is saved into file: ', filename)

#with open('test.txt', 'r') as f:
#    tmp = json.loads(f.read())

In [53]:
df['ingredient'].iloc[0:100]

0                       salt
1                     pepper
2                     butter
3                     garlic
4                      sugar
               ...          
95          virgin olive oil
96    extra virgin olive oil
97                    yellow
98              green onions
99           chicken breasts
Name: ingredient, Length: 100, dtype: object

In [141]:
import csv

file = '/Users/iskriyanavasileva/git/deep-food/data/mapping.csv'

In [134]:
input_file = csv.DictReader(open(file))

In [ ]:
## most common ingredients 
# 1. mapping from Excel file to recipe, Tab "mapping"
# 2. replacing them in ingredients and recipes
# 3. delete ingredients in Tab "delete"

## clean rest of recipes
# filter out classifier labels? 

In [ ]:
# mapping
# output - classifier_labels & out_of_the_fridge als input für one-hot-encoding
# one-hot encoding for only the output
# funktion - 

In [ ]:
# nach similarity check - die gefilterten im vollen Recipe Set nachschauen. 

In [144]:
# jupyter notebook