In [2]:
import numpy as np
import pandas as pd

# Load recipes

In [131]:
with np.load('simplified-recipes-1M_Issi.npz', allow_pickle=True) as data:
    recipes = data['recipes']
    ingredients = data['ingredients']

In [132]:
recipes.shape

(1067557,)

# Clean data: non-ingredients, non-specific ingredients etc.

In [4]:
recipes[0:5]

array([array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21]),
       array([ 198,  249,    2,  194, 1884,  791,  965,  423,   53,   48,  798,
         31,  362, 1031,   94,   26,    8]),
       array([ 328,  263,   62,   46,  445,   55, 1196,   82,  664,    3,  602,
         10,    7,    6,    1,  128,   61,  141,    0,  262,  140,  655,
         21,    8,   23,   84]),
       array([ 988, 1307]),
       array([  14, 1117,  998, 1010,    9,   30,   18,   29,  214, 1752, 1477,
          1,  132,  196,  658, 1301,   26,  113])], dtype=object)

In [5]:
recipes[0]

array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21])

In [6]:
ingredients[recipes[0]]

array(['basil leaves', 'focaccia', 'leaves', 'mozzarella', 'pesto',
       'plum tomatoes', 'rosemary', 'sandwiches', 'sliced', 'tomatoes'],
      dtype='<U39')

In [7]:
ingredients[0]

'salt'

In [8]:
file_delete = '/Users/iskriyanavasileva/git/deep-food/data/recipe_delete.csv'

In [9]:
df_delete = pd.read_csv(file_delete)

In [10]:
df_delete.head()

to_delete
0      white
1    extrace
2  vegetable
3     leaves
4     packed

In [11]:
np_delete = df_delete.to_numpy()

In [12]:
ingredients_l = [i for i in ingredients]

In [13]:
np_delete_l = [i[0] for i in np_delete]
np_delete_l[0:5]

['white', 'extrace', 'vegetable', 'leaves', 'packed']

In [14]:
ingredients[recipes[0]]

array(['basil leaves', 'focaccia', 'leaves', 'mozzarella', 'pesto',
       'plum tomatoes', 'rosemary', 'sandwiches', 'sliced', 'tomatoes'],
      dtype='<U39')

In [15]:
for i in ingredients[recipes[0]]:
    print(i, np_delete[0][0])

basil leaves white
focaccia white
leaves white
mozzarella white
pesto white
plum tomatoes white
rosemary white
sandwiches white
sliced white
tomatoes white


In [16]:
recipes[0]

array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21])

In [17]:
ingredients[recipes[0] != 'leaves']

/Users/iskriyanavasileva/opt/anaconda3/envs/deep-food/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


array([['salt', 'pepper', 'butter', ..., 'watercress leaves',
        'emerils essence', 'corn flakes cereal']], dtype='<U39')

In [18]:
test = np.delete(ingredients[recipes[0]], np.argwhere(ingredients[recipes[0]] == np_delete_l[3]))
test

array(['basil leaves', 'focaccia', 'mozzarella', 'pesto', 'plum tomatoes',
       'rosemary', 'sandwiches', 'sliced', 'tomatoes'], dtype='<U39')

In [19]:
ingredients[recipes[0]]

array(['basil leaves', 'focaccia', 'leaves', 'mozzarella', 'pesto',
       'plum tomatoes', 'rosemary', 'sandwiches', 'sliced', 'tomatoes'],
      dtype='<U39')

In [20]:
recipes_test = recipes[0:10]
#recipes_test

In [21]:
dict_ingr_ind = dict(enumerate(ingredients))

In [22]:
keys = ingredients
values = range(len(ingredients))

dict_ingr_ind_rev = dict(zip(keys, values))
#dict_ingr_ind_rev

In [23]:
#for k, v in dict_ingr_ind.items():
#    print(k, v)
#    print(dict_ingr_ind_rev[v])

In [24]:
recipes_test[0]

array([ 233, 2754,   42,  120,  560,  345,  150, 2081,   12,   21])

In [25]:
current_recipe = ingredients[recipes_test[0]]
elements_to_delete = np.intersect1d(current_recipe, np_delete)
mask_delete = np.isin(current_recipe, elements_to_delete)
print(mask_delete)
clean_recipe = current_recipe[~mask_delete]
clean_recipe

[False False  True False False False False False False False]


array(['basil leaves', 'focaccia', 'mozzarella', 'pesto', 'plum tomatoes',
       'rosemary', 'sandwiches', 'sliced', 'tomatoes'], dtype='<U39')

In [26]:
clean_recipe_idx = [dict_ingr_ind_rev[ingredient] for ingredient in clean_recipe]
clean_recipe_idx

[233, 2754, 120, 560, 345, 150, 2081, 12, 21]

In [27]:
clean_recipe_test = np.delete(recipes_test[0], 2)
clean_recipe_test

array([ 233, 2754,  120,  560,  345,  150, 2081,   12,   21])

In [28]:
#recipes_test_new = np.empty(recipes_test.shape)
recipes_test_new = []
#recipes_test_new = np.full(recipes_test.shape, None)
for recipe in range(len(recipes_test)):
    current_recipe = ingredients[recipes_test[recipe]]
    print(recipes_test[recipe])
    print(f'current_recipe {current_recipe}')
    print('------------------------------------')
    #for ingr in range(len(np_delete)):
        #np.delete(current_recipe, np.argwhere(current_recipe == np_delete[ingr]))
    #clean_recipe = np.delete(current_recipe, np.argwhere(np.intersect1d(current_recipe,np_delete)))
    #clean_recipe = current_recipe[current_recipe != np.intersect1d(current_recipe,np_delete)]
    #mask_delete = np.where(np.intersect1d(current_recipe,np_delete)) 
    #clean_recipe = np.delete(current_recipe, mask_delete) - not working because of index mismatch
    
    elements_to_delete = np.intersect1d(current_recipe,np_delete)
    mask_delete = np.isin(current_recipe, elements_to_delete) 
    print(mask_delete)
    clean_recipe = current_recipe[~mask_delete]
    
    #https://stackoverflow.com/questions/33529593/how-to-use-a-dictionary-to-translate-replace-elements-of-an-array
    clean_recipe_idx = [dict_ingr_ind_rev[ingredient] for ingredient in clean_recipe]
    #recipes_test_new.append(clean_recipe)
    recipes_test_new.append(clean_recipe_idx)
    #np.append(recipes_test_new, clean_recipe)
    print(f'clean_recipe {clean_recipe}')
    print('------------------------------------')
    
    #deleted ingridients and their indices
    deleted = current_recipe[mask_delete]
    
    indices_to_delete = np.isin(current_recipe, elements_to_delete).nonzero()[0]
    print(indices_to_delete)
    indices_to_delete = tuple(indices_to_delete)
    print(indices_to_delete)
    current_recipe2 = np.delete(current_recipe, indices_to_delete)
    np.delete(ingredients[recipes_test[recipe]], indices_to_delete)
    print(f'deleted {deleted}')
    print(f'current_recipe2 {current_recipe}')
    print('************************************')
    #np.delete(ingredients[recipes_test[i]], np.argwhere(ingredients[recipes_test[i]] == np_delete_l[3]))
    #print(ingredients[i])
    #print(np_delete_l)
    #print(ingredients)
    

[ 233 2754   42  120  560  345  150 2081   12   21]
current_recipe ['basil leaves' 'focaccia' 'leaves' 'mozzarella' 'pesto' 'plum tomatoes'
 'rosemary' 'sandwiches' 'sliced' 'tomatoes']
------------------------------------
[False False  True False False False False False False False]
clean_recipe ['basil leaves' 'focaccia' 'mozzarella' 'pesto' 'plum tomatoes' 'rosemary'
 'sandwiches' 'sliced' 'tomatoes']
------------------------------------
[2]
(2,)
deleted ['leaves']
current_recipe2 ['basil leaves' 'focaccia' 'leaves' 'mozzarella' 'pesto' 'plum tomatoes'
 'rosemary' 'sandwiches' 'sliced' 'tomatoes']
************************************
[ 198  249    2  194 1884  791  965  423   53   48  798   31  362 1031
   94   26    8]
current_recipe ['balsamic vinegar' 'boiling water' 'butter' 'cooking spray'
 'crumbled gorgonzola' 'currants' 'gorgonzola' 'grated orange' 'kosher'
 'kosher salt' 'orange rind' 'parsley' 'pine nuts' 'polenta' 'toasted'
 'vinegar' 'water']
----------------------------

In [130]:
recipes_test_new

[[233, 2754, 120, 560, 345, 150, 2081, 12, 21],
 [198, 249, 2, 1884, 791, 965, 423, 53, 48, 798, 31, 362, 1031, 26, 8],
 [263,
  62,
  46,
  445,
  55,
  1196,
  82,
  664,
  3,
  602,
  10,
  7,
  6,
  1,
  128,
  61,
  141,
  0,
  262,
  140,
  655,
  21,
  8,
  84],
 [988, 1307],
 [14,
  1117,
  998,
  1010,
  9,
  30,
  18,
  29,
  214,
  1752,
  1477,
  1,
  132,
  196,
  658,
  1301,
  26,
  113],
 [14, 458, 155, 16, 185, 193, 474, 1, 284, 323, 920, 0, 20, 26, 118],
 [131,
  669,
  724,
  208,
  2487,
  358,
  985,
  654,
  116,
  243,
  55,
  32,
  624,
  82,
  146,
  1240,
  1182,
  1032,
  325,
  337,
  15,
  260,
  2378,
  71,
  25,
  565,
  11,
  152,
  476,
  0,
  21,
  244,
  1270,
  8,
  133],
 [14,
  78,
  110,
  19,
  64,
  55,
  32,
  213,
  17,
  1540,
  3,
  79,
  9,
  30,
  87,
  119,
  365,
  10,
  7,
  25,
  1,
  744,
  175,
  3256,
  11,
  221,
  0,
  829,
  1594,
  425,
  8,
  166],
 [32, 300, 24, 179, 174, 388, 34, 87, 15, 4, 361, 38, 8, 112],
 [468, 37, 52, 28

In [ ]:
ingredients[recipes_test_new[0]]

In [ ]:
np.isin(ingredients, clean_recipe).nonzero()[0]

In [ ]:
ingredients[np.isin(clean_recipe, ingredients).nonzero()[0]]

In [ ]:
np.isin(ingredients, np_delete).nonzero()[0]

In [ ]:
recipes_test_new.shape

In [ ]:
ingredients[recipes_test[0]]

In [ ]:
np.delete(ingredients[recipes_test[0]], (2,3,7))

In [ ]:
for recipe in range(len(recipes_test)):
    current_recipe = ingredients[recipes_test[recipe]]
    print(f'current_recipe {current_recipe}')

In [ ]:
current_recipe = ingredients[recipes_test[0]]
current_recipe

### Tests for Selection and Deletion
https://stackoverflow.com/questions/47540800/how-to-select-all-elements-in-a-numpy-array-except-for-a-sequence-of-indices

In [ ]:
test_one = np.array(['A','C','B','E'])
test_one.shape

In [ ]:
test_two = np.array(['A','F','B'])

In [ ]:
np.where(np.intersect1d(test_one,test_two))

In [ ]:
interesect_elements = np.intersect1d(test_one,test_two)
interesect_elements

In [ ]:
mask_isin = np.isin(test_one, interesect_elements)
mask_isin

In [ ]:
test_one[~mask_isin]

In [ ]:
mask_new = [np.where(test_one == x)[0][0] for x in test_two]
mask_new

In [ ]:
test_res = np.delete(test_one, mask_new)
test_res

In [ ]:
test_clean = test_one[test_one != np.intersect1d(test_one.reshape(-1,1),test_two.reshape(-1,1))]
test_clean

In [ ]:
test_one1 = test_one

In [ ]:
test_one1 = np.delete(test_one1, 1, 0)
test_one1

In [ ]:
clean_recipe = current_recipe[current_recipe != np.intersect1d(current_recipe,np_delete)]
clean_recipe

In [ ]:
np.intersect1d(current_recipe,np_delete)
#np.where(np.in1d(current_recipe,np_delete))

In [ ]:
(current_recipe==np_delete).all()

In [ ]:
#for ingr in range(len(np_delete)):
np.delete(current_recipe, np.argwhere(current_recipe == np_delete[3]))
    #print(ingr)

In [ ]:
current_recipe

In [ ]:
np_delete[3]

In [ ]:
#ingredients == np_delete_l[3]
np.argwhere(ingredients == np_delete[3])

In [ ]:
ingredients[42]

In [ ]:
recipes_test

In [ ]:
for x in recipes_test:
    for y in x:
        print(ingredients[y])
        np.delete(ingredients[y], np.argwhere(ingredients[y] == np_delete_l[3]))

# Map Data

In [29]:
file_mapping = '/Users/iskriyanavasileva/git/deep-food/data/recipe_mapping.csv'

In [30]:
df_mapping = pd.read_csv(file_mapping, delimiter=';')

In [31]:
df_mapping.head()

recipes      classifier
0       chicken  chicken_breast
1      tomatoes          tomato
2          eggs             egg
3        onions           onion
4  black pepper          pepper

In [32]:
#mapping_dict = df_mapping.to_dict(orient='records')

In [38]:
df_mapping['classifier']

0      chicken_breast
1              tomato
2                 egg
3               onion
4              pepper
            ...      
281     chicken broth
282           pumpkin
283             flour
284              corn
285            tomato
Name: classifier, Length: 286, dtype: object

In [45]:
mapping_dict = dict(zip(df_mapping['recipes'], df_mapping['classifier']))

In [48]:
mapping_dict['chicken']

'chicken_breast'

In [47]:
mapping_dict

{'chicken': 'chicken_breast',
 'tomatoes': 'tomato',
 'eggs': 'egg',
 'onions': 'onion',
 'black pepper': 'pepper',
 'ground black pepper': 'pepper',
 'brown sugar': 'sugar',
 'garlic cloves': 'garlic',
 'unsalted butter': 'butter',
 'vanilla extract': 'vanilla',
 'parmesan': 'grated_cheese',
 'kosher salt': 'salt',
 'baking soda': 'baking powder',
 'cheddar': 'cheese',
 'parmesan cheese': 'grated_cheese',
 'cheddar cheese': 'cheese',
 'red pepper': 'paprika',
 'carrots': 'carrot',
 'bell pepper': 'paprika',
 'cayenne': 'pepper',
 'garlic powder': 'garlic',
 'cloves': 'clove',
 'white wine': 'wine',
 'peppers': 'paprika',
 'garlic minced': 'garlic',
 'heavy cream': 'cream',
 'lime juice': 'lemon juice',
 'ground cinnamon': 'cinnamon',
 'green onions': 'scallion',
 'virgin olive oil': 'oil',
 'granulated sugar': 'sugar',
 'chicken breast': 'chicken_breast',
 'ground beef': 'beef',
 'extra virgin olive oil': 'oil',
 'ground pepper': 'pepper',
 'wine vinegar': 'vinegar',
 'cayenne pepper'

In [46]:
test_dict = zip(df_mapping['recipes'], df_mapping['classifier'])

for i in test_dict:
    print(i)

('chicken', 'chicken_breast')
('tomatoes', 'tomato')
('eggs', 'egg')
('onions', 'onion')
('black pepper', 'pepper')
('ground black pepper', 'pepper')
('brown sugar', 'sugar')
('garlic cloves', 'garlic')
('unsalted butter', 'butter')
('vanilla extract', 'vanilla')
('parmesan', 'grated_cheese')
('kosher salt', 'salt')
('baking soda', 'baking powder')
('cheddar', 'cheese')
('parmesan cheese', 'grated_cheese')
('cheddar cheese', 'cheese')
('red pepper', 'paprika')
('carrots', 'carrot')
('bell pepper', 'paprika')
('cayenne', 'pepper')
('garlic powder', 'garlic')
('cloves', 'clove')
('white wine', 'wine')
('peppers', 'paprika')
('garlic minced', 'garlic')
('heavy cream', 'cream')
('lime juice', 'lemon juice')
('ground cinnamon', 'cinnamon')
('green onions', 'scallion')
('virgin olive oil', 'oil')
('granulated sugar', 'sugar')
('chicken breast', 'chicken_breast')
('ground beef', 'beef')
('extra virgin olive oil', 'oil')
('ground pepper', 'pepper')
('wine vinegar', 'vinegar')
('cayenne pepper'

In [50]:
type(clean_recipe)

numpy.ndarray

In [51]:
np_map = df_mapping['recipes'].to_numpy()

In [89]:
clean_recipe

array(['applesauce', 'baking powder', 'baking soda', 'brown sugar',
       'cinnamon', 'cranberries', 'eggs', 'extract', 'flour',
       'ground cinnamon', 'powder', 'salt', 'soda', 'sugar',
       'vanilla extract', 'zucchini'], dtype='<U39')

In [65]:
elements_to_map = np.intersect1d(clean_recipe, np_map)
print(elements_to_map)
mask_map = np.isin(clean_recipe, elements_to_map)
print(mask_map)
map_recipe = clean_recipe[mask_map]
map_recipe

['baking soda' 'brown sugar' 'eggs' 'ground cinnamon' 'vanilla extract']
[False False  True  True False False  True False False  True False False
 False False  True False]


array(['baking soda', 'brown sugar', 'eggs', 'ground cinnamon',
       'vanilla extract'], dtype='<U39')

In [129]:
mapped_recipe = [mapping_dict[ingredient] if (ingredient in mapping_dict.keys()) else ingredient for ingredient in clean_recipe ]
#print(clean_recipe)
print(mapped_recipe)
#mapping_dict
#mapping_dict['chicken']

['applesauce', 'baking powder', 'baking powder', 'sugar', 'cinnamon', 'cranberries', 'egg', 'extract', 'flour', 'cinnamon', 'powder', 'salt', 'soda', 'sugar', 'vanilla', 'zucchini']


In [115]:
'baking powder' in mapping_dict.values()

True

In [117]:
'baking powder' == mapping_dict['baking soda'] 

True

In [123]:
mapping_dict['baking powder']

KeyError: 'baking powder'

# Clean Recipes

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.load.html